#!/bin/sh

mtl_dir="/home/$USER/.medial_temporal_lobe"
USAGE="$0 add [url]"

# Check dependencies
if ! which uuidgen > /dev/null; then
    echo 'You need to install uuidgen.'
    exit 1
fi

# Required parameters
action="$1"
url="$2"
shift
shift

if test "$action" != 'add'; then
    echo Only the \"add\" action is supported right now.
    exit 1
elif test -z "$url"; then
    echo "$USAGE"
    exit 1
fi

while [ $# -gt 0 ]
do
    case "$1" in
        --mtl-dir) mtl_dir="$2"
            shift;;
        -t) tags="$2"
            shift;;
        -h) echo $USAGE
            exit;;
        -*) echo >&2 $USAGE
            exit 1;;
        *)  break;;
    esac
    shift
done

# Check that the memory directory exists.
if ! test -e "$mtl_dir"; then
    echo "You must create $mtl_dir."
    exit 1
fi

# Check whether the page exists
if grep -E "url=(https?)?$url" "$mtl_dir/memories/"*"/info"; then
    echo "$url" is already saved.
    exit 1
fi

# Check whether the tags are valid.
if echo "$tags" | grep '[^a-z_,]' > /dev/null; then
    echo 'Tags may only contain lowercase letters and underscores and must be separated by commas.'
    exit 1
fi

# Save the page.
uuid=$(uuidgen)
mkdir -p "$mtl_dir/memories/$uuid"
wget -O "$mtl_dir/memories/$uuid/source" "$url"

# Save some information.
echo "url=$url" > "$mtl_dir/memories/$uuid/info"
echo added=$(date --rfc-3339 ns) >> "$mtl_dir/memories/$uuid/info"

# Save tags
for tag in $(echo $tags | tr ',' '\n'); do
    mkdir -p "$mtl_dir/tags/$tag"
    (
        cd "$mtl_dir/tags/$tag"
        ln -s ../../memories/$uuid .
    )
done
